// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmV3m6N_ObASCCDWRaNTnYxoDCxf_3zdQ',
    appId: '1:578432148134:web:9dccb72611a18f67734a67',
    messagingSenderId: '578432148134',
    projectId: 'eahara-1546419310137',
    authDomain: 'eahara-1546419310137.firebaseapp.com',
    databaseURL: 'https://eahara-1546419310137.firebaseio.com',
    storageBucket: 'eahara-1546419310137.appspot.com',
    measurementId: 'G-SY48BJL4WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE1ZsZUAvkvM_B1kc8jAKX-8wN_4hCFwY',
    appId: '1:578432148134:android:bc2a709ce6684ef7734a67',
    messagingSenderId: '578432148134',
    projectId: 'eahara-1546419310137',
    databaseURL: 'https://eahara-1546419310137.firebaseio.com',
    storageBucket: 'eahara-1546419310137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDwWGJWAzpNU1gez5vJhaUcOMFpi-8Po',
    appId: '1:578432148134:ios:7ce1be50ab06c368734a67',
    messagingSenderId: '578432148134',
    projectId: 'eahara-1546419310137',
    databaseURL: 'https://eahara-1546419310137.firebaseio.com',
    storageBucket: 'eahara-1546419310137.appspot.com',
    iosBundleId: 'com.eahara.cust.flutterapp',
  );
}
